### ISSUE TITLE
Replacements Broken for Non-Jar Imports

### ISSUE THREAD

**Issue by BlueDragonX** [johnynek/bazel-deps#103]
https://github.com/johnynek/bazel-deps/pull/101 broke non-Jar replacements.

We have replacements for `io.getquill.quill-core` and `io.getquill.quill-cassandra` that point to  our own `scala_import` targets in order to fix some wierdness with `monix`. 

When `bazel-deps` generates the targets for them in `3rdparty/jvm` they are missing an `exports` section which causes them not to work.

Here's the replacements:
```
replacements:
  io.getquill:
    quill-cassandra:
      lang: scala
      target: "//3rdparty/jvm_manual/io/getquill:quill_cassandra"
    quill-core:
      lang: scala
      target: "//3rdparty/jvm_manual/io/getquill:quill_core"
```

Here's the `jvm_manual` targets we've defined:

```
load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "quill_core",
    jars = [
        "@io_getquill_quill_core_2_11//jar:file",
    ],
    visibility = [
        "//visibility:public",
    ],
    exports = [
        "//3rdparty/jvm/org/scala_lang:scala_library",
        "//3rdparty/jvm/org/scala_lang:scala_reflect",
        "//3rdparty/jvm/org/scalamacros:resetallattrs",
    ],
)

scala_import(
    name = "quill_cassandra",
    jars = [
        "@io_getquill_quill_cassandra_2_11//jar:file",
    ],
    visibility = [
        "//visibility:public",
    ],
    exports = [
        ":quill_core",
        "//3rdparty/jvm/com/datastax/cassandra:cassandra_driver_core",
        "//3rdparty/jvm/io/monix:monix_eval",
        "//3rdparty/jvm/io/monix:monix_execution",
        "//3rdparty/jvm/io/monix:monix_reactive",
        "//3rdparty/jvm/io/monix:monix_types",
        "//3rdparty/jvm/org/scala_lang:scala_library",
        "//3rdparty/jvm/org/scalamacros:resetallattrs",
    ],
)
```

And these are the targets that `bazel-deps` generates:

```
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "quill_cassandra",
    jars = [
        "//3rdparty/jvm_manual/io/getquill:quill_cassandra",
    ],
    visibility = [
        "//visibility:public",
    ],
)

scala_import(
    name = "quill_core",
    jars = [
        "//3rdparty/jvm_manual/io/getquill:quill_core",
    ],
    visibility = [
        "//visibility:public",
    ],
)
```

I can fix the build by adding `exports` to each of those targets which export the targets we've defined. However, `bazel-deps` overwrites this on every run.

Our temporary workaround is to require our `jvm_manual` targets directly, but this will break if we ever encounter quill as a transitive dependency.

**Comment by johnynek** [comment]
Ahh, yeah. Replacements are a case where we actually need to use `scala_library` + an export I think.

**Comment by johnynek** [comment]
@BlueDragonX that may work as well. I don't know what `scala_import` does with no jars. I know that scala_library works with only exports. I would argue that `scala_import` with no `jars` should perhaps fail since it is not really an import at that point. But it may work. I'd have to read the rule code again.

**Comment by BlueDragonX** [comment]
It works correctly for me when I change the generated build file to this:

```
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "quill_cassandra",
    jars = [
        "//3rdparty/jvm_manual/io/getquill:quill_cassandra",
    ],
    exports = [
        "//3rdparty/jvm_manual/io/getquill:quill_cassandra",
    ],
    visibility = [
        "//visibility:public",
    ],
)

scala_import(
    name = "quill_core",
    jars = [
        "//3rdparty/jvm_manual/io/getquill:quill_core",
    ],
    exports = [
        "//3rdparty/jvm_manual/io/getquill:quill_core",
    ],
    visibility = [
        "//visibility:public",
    ],
)
```

But I agree. Semantically it doesn't make any sense.

**Comment by ittaiz** [comment]
scala_import with no jars is how we group targets at Wix.
If you're familiar with maven it's somewhat analogous to depending on a
"pom".

**Comment by johnynek** [comment]
I think it should error if you have something in `jars` that is not a `jar`. In this example `//3rdparty/jvm_manual/io/getquill:quill_core` is another java provider, no?

@BlueDragonX what about removing the jars and just using exports? I assume that also works?

**Comment by BlueDragonX** [comment]
Yes, `//3rdparty/jvm_manual/io/getquill:quill_core` is another `scala_import`.

Removing the `jars` and leaving the `exports` works as well:
```
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "quill_cassandra",
    exports = [
        "//3rdparty/jvm_manual/io/getquill:quill_cassandra",
    ],
    visibility = [
        "//visibility:public",
    ],
)

scala_import(
    name = "quill_core",
    exports = [
        "//3rdparty/jvm_manual/io/getquill:quill_core",
    ],
    visibility = [
        "//visibility:public",
    ],
)
```

**Comment by johnynek** [comment]
cool. Can you send a PR to fix that up? I think it is just as simple as putting things into exports and not jars in the replacement section I linked to.

**Comment by BlueDragonX** [comment]
Sure, I'll see if I can make time to put something together.
