### ISSUE TITLE
Add header comment to generated workspace.bzl

### ISSUE THREAD

**Issue by drigz** [johnynek/bazel-deps#116]
[workspace.bzl](https://github.com/johnynek/bazel-deps/blob/109a2bf20b45bfbe199603b909e01033f04d277a/3rdparty/workspace.bzl) doesn't have a comment explaining that it is autogenerated. This means that devs unfamiliar with bazel-deps may waste time reading or editing this file, not knowing that the source of truth is dependencies.yaml.

I can see two approaches to avoid this.

1. Add a header comment to workspace.bzl, eg: `# This file is autogenerated by bazel-deps from ${g.depsFile}.`
1. Add an option for a custom header.

The first option is more invasive, but IMO more useful. What do you think?

**Comment by johnynek** [comment]
I agree the first option sounds better. Want to take a stab?
