### ISSUE TITLE
Document on how to integrate bazel-deps into own project

### ISSUE THREAD

**Issue by vmax** [johnynek/bazel-deps#126]
I didn't have success integrating raw repo via `git_repository` or `new_http_repository` because `bazel` complained that **my** workspace doesn't have `io_bazel_rules_scala`, `org_typelevel_paiges`, `com_monovore_decline` and it doesn't seem rational for me to add them into it. However, I've made [a repo with deployed build](https://github.com/vmax/bazel-deps-deploy) that is easier to use. So, to integrate it, include
```
git_repository(
    name = 'bazel_deps',
    remote = 'https://github.com/vmax/bazel-deps-deploy',
    commit = 'a15c2f64e099e78871ee78ff1f4e6bec5ec7ed4c'
)
```
into `WORKSPACE` and then binary is available as `bazel run @bazel_deps//:parse` 

Can it be made "official" (i.e. I transfer this repo to your org and you include instructions in `README`)?

**Comment by bjchambers** [comment]
+1 this would make it much easier to pull in. Another option would be something like:

1. `http_archive` of the deploy_jar
2. a bzl file that defined `bazel_deps` as coming from that jar

**Comment by guw** [comment]
Did anyone get it working directly from `johnynek/bazel-deps`? the repository listed above seems to be gone.

**Comment by vmax** [comment]
@guw sorry for letting you down, you can see the example of current usage [here](https://github.com/google/startup-os/blob/master/WORKSPACE#L279-L283)

**Comment by guw** [comment]
@vmax No worries. I'm consuming it that way. However, I'm trying to consume it directly from source. There are a few changes I need and potentially some changes I need to make. The jar in `oferb/startupos-binaries` doesn't contain those.

**Comment by johnynek** [comment]
I could probably publish a deploy jar to GitHub periodically. I actually haven’t looked at how to host jars on GitHub without checking it in, which I’d rather not do.

As stripe we just check the repo out in another location and bazel run from there.

**Comment by vmax** [comment]
@johnynek 

>how to host jars on GitHub without checking it in

You can store binaries (JARs in this case) [here](https://github.com/johnynek/bazel-deps/releases)
