### ISSUE TITLE
`runtime` deps from poms are exported by aether but not by coursier

### ISSUE THREAD

**Issue by kevingessner** [johnynek/bazel-deps#156]
The BUILD file generated for `org.mockito:mockito-core:2.7.20` ([pom](http://central.maven.org/maven2/org/mockito/mockito-core/2.7.20/mockito-core-2.7.20.pom)) is different with aether and coursier, because the coursier one doesn't include `runtime`-scoped deps

dependencies.yaml:
```
dependencies:
  org.mockito:
    mockito-core:
      lang: java
      version: "2.7.20"
```

`3rdparty/jvm/org/mockito/BUILD` with aether:

```
java_library(
    name = "mockito_core",
    exports = [
        "//3rdparty/jvm/net/bytebuddy:byte_buddy",
        "//3rdparty/jvm/net/bytebuddy:byte_buddy_agent",
        "//3rdparty/jvm/org/objenesis:objenesis",
        "//external:jar/org/mockito/mockito_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)
```

and with coursier:

```
java_library(
    name = "mockito_core",
    exports = [
        "//external:jar/org/mockito/mockito_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)
```

Note the three missing exports in the second BUILD file: these are `runtime` scoped deps, and mockito doesn't work without them.  Since they are mandatory, I think bazel-deps should export them with both coursier and aether.

**Comment by johnynek** [comment]
Actually can I talk you into adding this example to our coursier resolver tests?

**Comment by kevingessner** [comment]
sure thing

**Comment by kevingessner** [comment]
https://github.com/johnynek/bazel-deps/pull/158
