### ISSUE TITLE
replacements get private visibility

### ISSUE THREAD

**Issue by hsyed** [johnynek/bazel-deps#173]
Replacements jars are getting private visibility -- I am replacing protobuf-java and grpc-java. Please add an option to disable strict visibility.

**Comment by johnynek** [comment]
are you also declaring the those dependencies in your build or only putting them in replacements?

**Comment by hsyed** [comment]
They are being used in the build files for the sake of consistency -- but also because some of the third party deps need them as well.

**Comment by hsyed** [comment]
The external deps require some of the targets defined in grpc-java which we pull in via `new_git_repository`.  

`if your code is not accessing them?`

Sorry for the misunderstanding our code is accessing them. We'd like to reference the `grpc-java` targets via the tree generated by bazel-deps and not directly. Does this make sense ?

**Comment by akakitani** [comment]
Hey @johnynek, I've ran into this issue as well - I'm working on some libraries that depend on `scalapb-runtime`, so I'd like to have a replacement block that looks like this:

```yaml
replacements:
  com.trueaccord.scalapb:
    scalapb-runtime_2.11:
      lang: scala
      target: "@scala_proto_rules_scalapb_runtime//jar"
```

Like the previous comment mentioned, I think it'll be convenient if we could reference this dependency via `3rdparty/jvm/com/trueaccord/scalapb:scalapb_runtime_2.11`

Would changing this behavior just involve adding another entry here? https://github.com/johnynek/bazel-deps/blob/6585033409e09028852403ec15ec0c77851234be/src/scala/com/github/johnynek/bazel_deps/Writer.scala#L235-L238
