### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by gdeest** [johnynek/bazel-deps#197]
I am investigating how to replace SBT with Bazel in a project. This project currently uses the `sbt-license-report` plugin to extract licensing information for all (direct and transitive) dependencies. Would it be possible for `bazel-deps` to support this use-case ?

It looks like Scala rules does not support the `licenses` field per se, but they can be defined in a per-package fashion using a top-level `licenses` call.

cc @aherrmann

**Comment by pauldraper** [comment]
Every rule supports licenses https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes

(Macros don't though.)

**Comment by gdeest** [comment]
Indeed !

Unfortunately, I realized later on that it only supports license _types_, such as "permissive", "restricted", etc. which unfortunately won't suffice for our needs. I thus think we can close this.
