### ISSUE TITLE
What do we think of making a release/tag for the current state of the code base?

### ISSUE THREAD

**Issue by haikalpribadi** [johnynek/bazel-deps#202]
Hi @johnynek,

I've finally managed to migrate all our maven dependencies over using the coursier resolve last night. I've also managed to see how it increments the generated `BUILD` files for the artifacts. `bazel-deps` is amazing! We'll be using this at Grakn going forward. Thank you (and your team) for the great work!

I would like to add a dependency to this `bazel-deps` repository so we can automate the toolings in our repo. However, I noticed that there are no releases/tags on this repo, which means we could only depend on the archived zip. This is less ideal as we won't have the stability of a fixed version.

What do you think of making a release/tag for the current state of the code base and so we can depend on this repository by repo?

Thank you!

**Comment by johnynek** [comment]
What we do is depend on the particular git sha that we want. Will that work for you for now?

We could imagine adding versions but I haven’t seen the need with the ability to do git sha.

**Comment by haikalpribadi** [comment]
Yes, that makes sense. Thank you! I'll close this issue now.
