### ISSUE TITLE
consider using Coursier for artifact resolution

### ISSUE THREAD

**Issue by johnynek** [johnynek/bazel-deps#23]
https://github.com/alexarchambault/coursier

It seems to have a parallelism story. Currently, running this code on a big repo may take 5 minutes.

**Comment by petroseskinder** [comment]
@johnynek this would replace aether for resolving dependencies? That looks very promising. 
> Currently, running this code on a big repo may take 5 minutes.
How long does it take with aether?

**Comment by johnynek** [comment]
@petroseskinder we finally got around to this: https://github.com/johnynek/bazel-deps/pull/145

**Comment by petroseskinder** [comment]
@johnynek nice! I do like that you kept aether as a non-default option. From what I understand, you are using Coursier to parallelize fetching the graph of POM files and then running your prior graph normalization on this graph?

**Comment by johnynek** [comment]
actually, we kept aether as the *default* now, but may change that. Otherwise, yes: we only use coursier to fetch poms in parallel.
