### ISSUE TITLE
Bazel 0.23.0 compatibility

### ISSUE THREAD

**Issue by thundergolfer** [johnynek/bazel-deps#241]
As of today Bazel `0.23.0` has been released -> https://github.com/bazelbuild/bazel/issues/6495. Throwing up this issue to track `0.23.0` compatibility. 

The error appears pretty simple to (short-term) fix: 

```
ERROR: /private/var/tmp/_bazel_jbelotti/a8760d5b2ababb5105592d0d98b41ced/external/io_bazel_rules_scala/scala/scala.bzl:111:13:
Using cfg = "data" on an attribute is a noop and no longer supported. 
Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
```

**Comment by gertvdijk** [comment]
The `rules_scala` version referenced in `WORKSPACE` is pretty old, from July 2018.

https://github.com/johnynek/bazel-deps/blob/e3f77e22d9f5b070915067a766607cfc96835c98/WORKSPACE#L6-L10

If you update this revision to master, currently @ `7ea9079f15ba85df21e442f29cd0e37424b09ae7`, does that solve the problem? (Or it may introduce new... :smile: )

**Comment by thundergolfer** [comment]
> (Or it may introduce new... 😄 )

Very possibly.

**Comment by johnynek** [comment]
rules_scala should work. An update to the sha will probably fix.
