### ISSUE TITLE
format-deps drops generateNeverlink

### ISSUE THREAD

**Issue by mcamenzind** [johnynek/bazel-deps#298]
Executing `format-deps` on the `dependencies.yaml` file removes the `generateNeverlink: True`.

**How to reproduce**
`~/.bazel-deps-cache/v0.1-9 format-deps -d "$REPO_ROOT/$DEPENDENCIES_FILE" -o`

You will notice that the manually added `generateNeverlink` entries were dropped.

**Comment by johnynek** [comment]
Looks like toDoc here ignores that field:

https://github.com/johnynek/bazel-deps/blob/3bed1b71bf94a62b566d6d98f119f2708b28c367/src/scala/com/github/johnynek/bazel_deps/DepsModel.scala#L683

would be an easy fix.

Do you want to send a PR?
