### ISSUE TITLE
Can i user this  on windows?

### ISSUE THREAD

**Issue by wangzhichao-github** [johnynek/bazel-deps#304]

**Comment by charlesoconor** [comment]
No

**Comment by johnynek** [comment]
Sorry, I don't know the answer to this. I don't really know why not, but maybe it doesn't work.

**Comment by johnynek** [comment]
Note this user seems to be using windows:

https://github.com/johnynek/bazel-deps/issues/255

**Comment by johnynek** [comment]
please re-open if you try and see that it fails.
