### ISSUE TITLE
Parser Failure and Inability to Import Package

### ISSUE THREAD

**Issue by petroseskinder** [johnynek/bazel-deps#45]
## Context
I was trying to build a simple maven project with the following external dependencies: 

```python
dependencies:
  org.powermock:
    powermock-module-junit4:
      version: "1.5.1"
      lang: java

    powermock-api-mockito:
      version: "1.5.1"
      lang: java

  com.github.stefanbirkner:
    system-rules:
      version: "1.14.0"
      lang: java
      exclude: "junit:junit-dep"  # <--- THIS IS WHERE WEIRD BEHAVIOR DERIVES FROM

  junit:
    junit:
      version: "4.11"
      lang: java
```
### Parser Issues
I found that the inclusion of the "excludes" statement led to a number of issues with the parser. In particular it led to the following error message. 
```bash
[ERROR]: Failed to parse dependencies.yaml.
DecodingFailure([A]Set[A], List(DownField(exclude), DownField(system-rules), DownField(com.github.stefanbirkner), DownField(dependencies)))
```
It's clear that the tool is unable to generate transitive dependencies for com.github.stefanbirkner group. **However it is unclear why this is the case.**

### Importing Package Issues

When I comment out the exclude line, the BUILD files are successfully generated. However, when I try to build the target that depends on com.github.stefanbirkner, I receive the following errors

``` 
src/test/java/com/example/javamavenjunithelloworld/HelloWithTestsIT.java:5: error: package org.junit.contrib.java.lang.system does not exist
```
This is a package within [com.github.stefanbirkner](https://github.com/stefanbirkner/system-rules/blob/master/src/main/java/org/junit/contrib/java/lang/system/StandardOutputStreamLog.java), indicating that the package was unsuccessfully included.

## Potential Cause
**Versioning Issue?**
I do know that the missing package org.junit.contrib.java.lang.system is a deprecated junit package that is now included within stefanbirkner's system rules. So perhaps it is some sort of versioning issue with junit. According to it's [pom.xml](https://search.maven.org/remotecontent?filepath=com/github/stefanbirkner/system-rules/1.14.0/system-rules-1.14.0.pom), system-rules depends on junit-dep [4.9, ). However, junit-dep has been deprecated after junit-4.11

**Comment by johnynek** [comment]
The first issue is that it is `exclude: [ ]`, note it is an array, not a string it is expecting. I think that is your parser error. Sadly, the parser errors are not very helpful in this regard.

As to the second issue, taking a look at the pom:
https://github.com/stefanbirkner/system-rules/blob/master/pom.xml#L58

it seems that pom uses version ranges. This is literally the first time I've seen that. I don't know what this returns here:
https://github.com/johnynek/bazel-deps/blob/master/src/scala/com/github/johnynek/bazel_deps/Resolver.scala#L167

my guess is that it just returns that string. I don't know at the moment what that's going to do, but it shouldn't silently fail.

We just use Aether to walk the graph: https://github.com/johnynek/bazel-deps/blob/master/src/scala/com/github/johnynek/bazel_deps/Resolver.scala#L158
so, either Aether supports those ranges or it does not.

**Comment by petroseskinder** [comment]
Thank you. That resolved the first issue. Anyway you can add an example in the docs, or in your dependencies.yaml file. I had previously sifted through the docs/code, and couldn't find any.

As for the second issue, good eye. I'll close this issue and open a separate issue that specifies that exclusively.
