### ISSUE TITLE
Generate third_party/ instead of 3rdparty/ (or make it configurable)

### ISSUE THREAD

**Issue by cgrushko** [johnynek/bazel-deps#59]
Some languages, such as Python and Go, require directories to have legal symbol names, so they can't begin with digits or contain dashes, for example.

**Comment by johnynek** [comment]
is it not configurable? I think it is:

https://github.com/johnynek/bazel-deps/blob/master/src/scala/com/github/johnynek/bazel_deps/DepsModel.scala#L858

looks like that is not documented.

**Comment by johnynek** [comment]
added documentation: https://github.com/johnynek/bazel-deps/commit/6d1498cb8ed10f5a1ade78698790b8bddc8e6303

**Comment by cgrushko** [comment]
Ah, nice! works great :)
