### ISSUE TITLE
Allow user to avoid creating `declare_maven`

### ISSUE THREAD

**Issue by cgrushko** [johnynek/bazel-deps#60]
I'm guessing it allows Stripe to customize the callback?
I'm not sure it's useful for most users. Perhaps allow users to tell bazel-deps "create a callback inside `3rdparty/workspace.bzl` while you write it?

**Comment by johnynek** [comment]
yes. Many companies have their own nexus or maven cache. I think it is common to want to customize that industrially. That is the mechanism.

We can make it so a default works. PR?

**Comment by ittaiz** [comment]
@johnynek can you explain how customizing the callback helps you with your internal artifactory? I think I'm missing something
