### ISSUE TITLE
Support annotation processors

### ISSUE THREAD

**Issue by cgrushko** [johnynek/bazel-deps#62]
For example, [auto_value](https://github.com/google/auto/tree/master/value) needs to run an annotation processor as part of a build. 

The BUILD file that bazel-deps produces for auto-value is something like:
```
java_library(
    name = "auto_value",
    visibility = [
        "//visibility:public",
    ],
    exports = [
        "//external:jar/com/google/auto/value/auto_value",
    ],
)
```

In order to support annotation processing, one needs to change it to

```
java_library(
    name = "auto_value",
    exported_plugins = [
        ":auto_value_plugin",
    ],
    visibility = [
        "//visibility:public",
    ],
    exports = [
        "//external:jar/com/google/auto/value/auto_value",
    ],
)

java_plugin(
    name = "auto_value_plugin",
    processor_class = "com.google.auto.value.processor.AutoValueProcessor",
    deps = [
        "//external:jar/com/google/auto/value/auto_value",
    ],
)
```

Note the `exported_plugins` and `processor_class` attributes.

**Proposal:**
A `dependencies` entry in the yaml file will contain a field named `processor_class`. When it's present, bazel-deps will create a BUILD file similar to the example above.

**Comment by johnynek** [comment]
this proposal seems fine to me. Want to start a PR?

**Comment by cgrushko** [comment]
Sure. Can you give me code pointers? Where to start modifying?

**Comment by greggdonovan** [comment]
Thanks! We can close this now that #93 is merged.

**Comment by cgrushko** [comment]
Niiiiice :D
