### ISSUE TITLE
Generated BUILD files are not formatted according to buildifier

### ISSUE THREAD

**Issue by damienmg** [johnynek/bazel-deps#73]
See https://bazel-review.googlesource.com/c/continuous-integration/+/17250/2..3 for an example of result of buildifier running on 3rdparty files.

**Comment by johnynek** [comment]
yeah, I'm not sure I really want to go all the way to making this work given buildifier exists and might even change style's later.

Our approach is to run build formatting after this tool.

I have made efforts for the output to be somewhat clean, but this is a somewhat low priority issue given very limited dev cycles.

**Comment by damienmg** [comment]
That's fair. FTR I would be satisfied with just the shell wrapper trying to call buildifier after the generation or warning if buildifier does not exists in the path :)

**Comment by johnynek** [comment]
that sounds good.
