### ISSUE TITLE
Macro-support workaround breaks IntelliJ plugin

### ISSUE THREAD

**Issue by gkossakowski** [johnynek/bazel-deps#81]
Apparently, the pattern bazel-deps uses to get around ijar+scala macros issue confuses the IntelliJ plugin. The problem is with using "//jar:file".

See the corresponding issue in the intellij plugin: https://github.com/bazelbuild/intellij/issues/142
I'm cross-posting between repos because it's not clear whether this issue should be fixed by bazel-deps, the intellij plugin or maybe even bazel core.

The discussion which points at bazel-deps as a source of problem is here: https://github.com/bazelbuild/intellij/issues/97#issuecomment-310906994

**Comment by johnynek** [comment]
we have to do it this way until the scala rules can support macros in jars. `maven_jar` will not work.

The solution is in the scala rules to make a `scala_jar` repository rule which can not use ijar on the output, but give a sane java_provider.

**Comment by ittaiz** [comment]
I'll try and expedite the scala_import rule as fast as I can and once it's
in baze_deps will be able o use it

**Comment by gkossakowski** [comment]
Ittai, Do you have a sense of how much work is left?
Our homegrown aspects that generate intellij project files are subtly broken by recent bazel/rules_scala upgrade and i'm trying to estimate whether i should dive into fixing them

**Comment by gkossakowski** [comment]
I found a workaround for our internal issues so I'm not on fire anymore but still very interested in getting the official intellij plugin to work.

**Comment by ittaiz** [comment]
Excellent. I'll update as soon as I have progress

**Comment by kevingessner** [comment]
I believe #101 has fixed this -- scala deps work in intellij for me these days.

**Comment by johnynek** [comment]
reopen if there is an issue.
