### ISSUE TITLE
Add a `check` function to gen_maven_deps.sh to verify that generated files match what's expected from the Yaml

### ISSUE THREAD

**Issue by greggdonovan** [johnynek/bazel-deps#85]
See [discussion here](https://github.com/bazelbuild/BUILD_file_generator/pull/19/files#r144173015).

We run `check-deps.sh` in CI to make sure that the yaml and generated files are in sync. It'd be nice to move the logic of the check into bazel-deps.

**Comment by johnynek** [comment]
This is a good idea. It shouldn't be too hard since we don't actually have to parse the files, just diff them.

**Comment by kevingessner** [comment]
I'm going to take a stab at this.
